clear all; clc; close all;

deviceReader.Driver = 'CoreAudio';
deviceReader = audioDeviceReader;

aPR = audioPlayerRecorder('Device', 'Aggregate Device',...
    'SampleRate',fs, ...
    'BitDepth','16-bit integer', ...
    'SupportVariableSize',true, ...
    'BufferSize', Buffersize, ...
    'PlayChannelMapping',[1,2], ...
    'RecorderChannelMapping',[1,2]);
